#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar\"'"

# external bar
yabai -m config external_bar all:27:0.0

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# space labels
# yabai -m space 1 --label chat
# yabai -m space 2 --label pdtive
# yabai -m space 3 --label notion
# yabai -m space 4 --label browser
# yabai -m space 5 --label misc1
# yabai -m space 6 --label misc2
# yabai -m space 7 --label code
# yabai -m space 8 --label finder

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  7
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# external bar
# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar main:25:0
# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
# yabai -m config external_bar all:25:25

# window border
yabai -m config window_border               off
yabai -m config window_border_width         0
yabai -m config active_window_border_color  0xFFA4F64A
yabai -m config normal_window_border_color  0xFF3e4050
yabai -m config insert_feedback_color       0xffd75f5f

yabai -m rule --add app="^Spotify.*$" sticky=off layer=above manage=off
yabai -m rule --add app="^QuickTime*.*$" sticky=off layer=above manage=off
yabai -m rule --add app="^Zoom*.*$" sticky=off layer=above manage=off
yabai -m rule --add app="^Things*.*$" sticky=on manage=off

# yabai -m rule --add app="^Discord.*$" display=^1
# yabai -m rule --add app="^Things.*$" display=^2
# yabai -m rule --add app="^Evernote.*$" display=^3
# yabai -m rule --add app="^Brave*.*$" display=^4
# yabai -m rule --add app="^iTerm.*$" display=^6
# yabai -m rule --add app="^Logseq.*$" display=^7

# yabai -m signal --add event=display_changed action="python3 ~/.config/yabai/padding.py"

echo "yabai configuration loaded.."
